# Generated by Django 2.2.14 on 2020-12-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20201121_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alumno_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
